apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  labels:
    type: amazonEBS 
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0969abd2dcb0e2204
    fsType: ext4
