apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: nginx
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: nodeapp-key
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          limits:
            memory: 1Gi
        ports:
        - name: nginx 
          containerPort: 80
          hostPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
      volumes:
          - name: config-volume
            configMap:
              name: nginx-config

