apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:""
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: ""
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 1080
      protocol: TCP
    - port: 443
      name: https
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx

