apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:480901666750:certificate/7a65ae85-dd57-4fc0-b911-f0b7fb78f54d
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 1080
      protocol: TCP
    - port: 443
      name: https
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx

