apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: node-app
  name: node-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      imagePullSecrets:
      - name: nodeapp-key
      containers:
      - image: rohanjoseph89/spacio:nodeappv2
        name: node-app
        resources:
          limits:
            memory: 1Gi
        ports:
        - name: node-app
          containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /opt/app/config
      volumes:
          - name: config-volume
            configMap:
              name: database-config
