apiVersion: v1
kind: Service
metadata:
  labels:
    name: node-app
  name: node-app
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
  selector:
    app: node-app

